[workspace]

members = [
	"dynatos",
	"dynatos-builder",
	"dynatos-builder-macros",
	"dynatos-context",
	"dynatos-html",
	"dynatos-html-macros",
	"dynatos-html-parser",
	"dynatos-loadable",
	"dynatos-reactive",
	"dynatos-reactive-sync",
	"dynatos-router",
	"dynatos-title",
	"dynatos-util",
]
resolver = "2"

[workspace.dependencies]

# Workspace members
dynatos = { path = "dynatos" }
dynatos-builder = { path = "dynatos-builder" }
dynatos-builder-macros = { path = "dynatos-builder-macros" }
dynatos-context = { path = "dynatos-context" }
dynatos-html = { path = "dynatos-html" }
dynatos-html-macros = { path = "dynatos-html-macros" }
dynatos-html-parser = { path = "dynatos-html-parser" }
dynatos-loadable = { path = "dynatos-loadable" }
dynatos-reactive = { path = "dynatos-reactive" }
dynatos-reactive-sync = { path = "dynatos-reactive-sync" }
dynatos-router = { path = "dynatos-router" }
dynatos-title = { path = "dynatos-title" }
dynatos-util = { path = "dynatos-util" }

# zutil
zutil-cloned = { git = "https://github.com/Zenithsiz/zutil", rev = "978fa5df733d59fc691812ce2fa6072bf901dc7f" }

anyhow = "1.0.94"
convert_case = "0.6.0"
duplicate = "2.0.0"
extend = "1.2.0"
itertools = "0.13.0"
js-sys = "0.3.76"
parking_lot = "0.12.3"
pin-project = "1.1.7"
proc-macro2 = "1.0.92"
quote = "1.0.37"
syn = "2.0.90"
tracing = "0.1.41"
tracing-subscriber = "0.3.19"
tracing-web = "0.1.3"
unicode-xid = "0.2.6"
url = "2.5.4"
wasm-bindgen = "0.2.99"
wasm-bindgen-futures = "0.4.49"
web-sys = "0.3.76"

[workspace.lints]

clippy.allow_attributes = "warn"
clippy.allow_attributes_without_reason = "warn"
clippy.cast_lossless = "warn"
clippy.checked_conversions = "warn"
clippy.clear_with_drain = "warn"
clippy.clone_on_ref_ptr = "warn"
clippy.cloned_instead_of_copied = "warn"
clippy.collection_is_never_read = "warn"
clippy.copy_iterator = "warn"
clippy.debug_assert_with_mut_call = "warn"
clippy.default_trait_access = "warn"
clippy.deref_by_slicing = "warn"
clippy.doc_markdown = "warn"
clippy.empty_drop = "warn"
clippy.empty_enum_variants_with_brackets = "warn"
clippy.empty_line_after_doc_comments = "warn"
clippy.empty_line_after_outer_attr = "warn"
clippy.empty_structs_with_brackets = "warn"
clippy.equatable_if_let = "warn"
clippy.expl_impl_clone_on_copy = "warn"
clippy.explicit_deref_methods = "warn"
clippy.explicit_into_iter_loop = "warn"
clippy.explicit_iter_loop = "warn"
clippy.fallible_impl_from = "warn"
clippy.filter_map_next = "warn"
clippy.flat_map_option = "warn"
clippy.fn_params_excessive_bools = "warn"
clippy.fn_to_numeric_cast_any = "warn"
clippy.format_push_string = "warn"
clippy.from_iter_instead_of_collect = "warn"
clippy.if_then_some_else_none = "warn"
clippy.ignored_unit_patterns = "warn"
clippy.implicit_clone = "warn"
clippy.implicit_hasher = "warn"
clippy.inconsistent_struct_constructor = "warn"
clippy.index_refutable_slice = "warn"
clippy.inefficient_to_string = "warn"
clippy.into_iter_without_iter = "warn"
clippy.iter_filter_is_ok = "warn"
clippy.iter_filter_is_some = "warn"
clippy.iter_on_empty_collections = "warn"
clippy.iter_on_single_items = "warn"
clippy.iter_over_hash_type = "warn"
clippy.iter_with_drain = "warn"
clippy.iter_without_into_iter = "warn"
clippy.large_futures = "warn"
clippy.large_stack_arrays = "warn"
clippy.large_stack_frames = "warn"
clippy.large_types_passed_by_value = "warn"
clippy.let_underscore_must_use = "warn"
clippy.let_underscore_untyped = "warn"
clippy.lossy_float_literal = "warn"
clippy.macro_use_imports = "warn"
clippy.manual_assert = "warn"
clippy.manual_c_str_literals = "warn"
clippy.manual_clamp = "warn"
clippy.manual_instant_elapsed = "warn"
clippy.manual_is_variant_and = "warn"
clippy.manual_let_else = "warn"
clippy.manual_ok_or = "warn"
clippy.manual_string_new = "warn"
clippy.map_err_ignore = "warn"
clippy.map_unwrap_or = "warn"
clippy.match_same_arms = "warn"
clippy.match_wild_err_arm = "warn"
clippy.match_wildcard_for_single_variants = "warn"
clippy.maybe_infinite_iter = "warn"
clippy.mismatching_type_param_order = "warn"
clippy.missing_assert_message = "warn"
clippy.missing_asserts_for_indexing = "warn"
clippy.missing_const_for_fn = "warn"
clippy.missing_fields_in_debug = "warn"
clippy.mixed_read_write_in_expression = "warn"
clippy.multiple_unsafe_ops_per_block = "warn"
clippy.must_use_candidate = "warn"
clippy.mut_mut = "warn"
clippy.mutex_atomic = "warn"
clippy.mutex_integer = "warn"
clippy.naive_bytecount = "warn"
clippy.needless_bitwise_bool = "warn"
clippy.needless_collect = "warn"
clippy.needless_continue = "warn"
clippy.needless_for_each = "warn"
clippy.needless_pass_by_ref_mut = "warn"
clippy.needless_pass_by_value = "warn"
clippy.needless_raw_string_hashes = "warn"
clippy.needless_raw_strings = "warn"
clippy.negative_feature_names = "warn"
clippy.no_effect_underscore_binding = "warn"
clippy.non_send_fields_in_send_ty = "warn"
clippy.nonstandard_macro_braces = "warn"
clippy.option_as_ref_cloned = "warn"
clippy.option_option = "warn"
clippy.or_fun_call = "warn"
clippy.partial_pub_fields = "warn"
clippy.path_buf_push_overwrite = "warn"
clippy.ptr_as_ptr = "warn"
clippy.ptr_cast_constness = "warn"
clippy.pub_underscore_fields = "warn"
clippy.pub_without_shorthand = "warn"
clippy.range_minus_one = "warn"
clippy.range_plus_one = "warn"
clippy.rc_buffer = "warn"
clippy.rc_mutex = "warn"
clippy.read_zero_byte_vec = "warn"
clippy.readonly_write_lock = "warn"
clippy.redundant_clone = "warn"
clippy.redundant_else = "warn"
clippy.redundant_feature_names = "warn"
clippy.redundant_pub_crate = "warn"
clippy.redundant_type_annotations = "warn"
clippy.ref_as_ptr = "warn"
clippy.ref_binding_to_reference = "warn"
clippy.ref_option_ref = "warn"
clippy.rest_pat_in_fully_bound_structs = "warn"
clippy.return_self_not_must_use = "warn"
clippy.same_functions_in_if_condition = "warn"
clippy.semicolon_if_nothing_returned = "warn"
clippy.semicolon_outside_block = "warn"
clippy.should_panic_without_expect = "warn"
clippy.significant_drop_in_scrutinee = "warn"
clippy.significant_drop_tightening = "warn"
clippy.stable_sort_primitive = "warn"
# TODO: `clippy.std_instead_of_alloc`, once we migrate to `no_std` where we can.
clippy.std_instead_of_core = "warn"
clippy.str_split_at_newline = "warn"
clippy.str_to_string = "warn"
clippy.string_lit_as_bytes = "warn"
clippy.string_to_string = "warn"
clippy.struct_excessive_bools = "warn"
clippy.struct_field_names = "warn"
clippy.suspicious_operation_groupings = "warn"
clippy.trait_duplication_in_bounds = "warn"
clippy.transmute_undefined_repr = "warn"
clippy.trivial_regex = "warn"
clippy.trivially_copy_pass_by_ref = "warn"
clippy.try_err = "warn"
clippy.tuple_array_conversions = "warn"
clippy.type_repetition_in_bounds = "warn"
clippy.unicode_not_nfc = "warn"
clippy.uninhabited_references = "warn"
clippy.uninlined_format_args = "warn"
clippy.unnecessary_box_returns = "warn"
clippy.unnecessary_join = "warn"
clippy.unnecessary_safety_comment = "warn"
clippy.unnecessary_safety_doc = "warn"
clippy.unnecessary_self_imports = "warn"
clippy.unnecessary_struct_initialization = "warn"
clippy.unnecessary_wraps = "warn"
clippy.unneeded_field_pattern = "warn"
clippy.unnested_or_patterns = "warn"
clippy.unsafe_derive_deserialize = "warn"
clippy.unused_async = "warn"
clippy.unused_peekable = "warn"
clippy.unused_self = "warn"
clippy.unwrap_used = "warn"
clippy.use_self = "warn"
clippy.used_underscore_binding = "warn"
clippy.useless_let_if_seq = "warn"
clippy.verbose_file_reads = "warn"
clippy.wildcard_dependencies = "warn"
clippy.zero_sized_map_values = "warn"
