[workspace]

members = ["dynatos", "dynatos-reactive"]
resolver = "2"

[workspace.dependencies]

# Workspace members
dynatos = { path = "dynatos" }
dynatos-reactive = { path = "dynatos-reactive" }

duplicate = "1.0.0"
