[workspace]

members = [
	"dynatos",
	"dynatos-builder",
	"dynatos-builder-macros",
	"dynatos-context",
	"dynatos-html",
	"dynatos-loadable",
	"dynatos-reactive",
	"dynatos-router",
	"dynatos-title",
	"dynatos-util",
]
resolver = "2"

[workspace.dependencies]

# Workspace members
dynatos = { path = "dynatos" }
dynatos-builder = { path = "dynatos-builder" }
dynatos-builder-macros = { path = "dynatos-builder-macros" }
dynatos-context = { path = "dynatos-context" }
dynatos-html = { path = "dynatos-html" }
dynatos-loadable = { path = "dynatos-loadable" }
dynatos-reactive = { path = "dynatos-reactive" }
dynatos-router = { path = "dynatos-router" }
dynatos-title = { path = "dynatos-title" }
dynatos-util = { path = "dynatos-util" }

anyhow = "1.0.79"
convert_case = "0.6.0"
duplicate = "1.0.0"
extend = "1.2.0"
itertools = "0.12.1"
js-sys = "0.3.68"
pin-cell = "0.2.0"
pin-project = "1.1.4"
quote = "1.0.35"
syn = "2.0.50"
tracing = "0.1.40"
tracing-subscriber = "0.3.18"
tracing-web = "0.1.3"
url = "2.5.0"
wasm-bindgen = "0.2.91"
wasm-bindgen-futures = "0.4.41"
web-sys = "0.3.68"

[workspace.lints]

clippy.map_unwrap_or = "warn"
clippy.flat_map_option = "warn"
clippy.must_use_candidate = "warn"
clippy.semicolon_if_nothing_returned = "warn"
clippy.manual_assert = "warn"
clippy.explicit_into_iter_loop = "warn"
clippy.needless_pass_by_value = "warn"
clippy.let_underscore_untyped = "warn"
clippy.missing_const_for_fn = "warn"
clippy.non_send_fields_in_send_ty = "warn"
