[workspace]

members = [
	"dynatos",
	"dynatos-context",
	"dynatos-logger",
	"dynatos-reactive",
	"dynatos-util",
]
resolver = "2"

[workspace.dependencies]

# Workspace members
dynatos = { path = "dynatos" }
dynatos-context = { path = "dynatos-context" }
dynatos-logger = { path = "dynatos-logger" }
dynatos-reactive = { path = "dynatos-reactive" }
dynatos-util = { path = "dynatos-util" }

anyhow = "1.0.79"
duplicate = "1.0.0"
extend = "1.2.0"
js-sys = "0.3.67"
tracing = "0.1.40"
tracing-subscriber = "0.3.18"
tracing-web = "0.1.3"
wasm-bindgen = "0.2.90"
web-sys = "0.3.67"
