[package]
name = "counter"
version = "0.1.0"
edition = "2021"

[dependencies]

dynatos = { workspace = true }
dynatos-html = { workspace = true }
dynatos-logger = { workspace = true }
dynatos-reactive = { workspace = true }
dynatos-util = { workspace = true }

anyhow = { workspace = true }
console_error_panic_hook = { workspace = true }
extend = { workspace = true }
tracing = { workspace = true }
wasm-bindgen = { workspace = true }
web-sys = { workspace = true }
