[package]
name    = "dynatos-egui"
version = "0.1.0"
edition = "2021"

[dependencies]

dynatos-reactive = { workspace = true }

egui    = { workspace = true }
tracing = { workspace = true }

[lints]
workspace = true
