[package]
name    = "dynatos-util"
version = "0.1.0"
edition = "2024"

[dependencies]

anyhow    = { workspace = true }
duplicate = { workspace = true }
extend    = { workspace = true }

[lints]
workspace = true
