[package]
name    = "dynatos-world"
version = "0.1.0"
edition = "2021"

[dependencies]

derive_more = { workspace = true, features = ["full"] }
parking_lot = { workspace = true }

[lints]
workspace = true
