[package]
name = "dynatos-macros"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]

derive_utils = { workspace = true }
quote = { workspace = true }
syn = { workspace = true }

[lints]
workspace = true
