[package]
name    = "dynatos-reactive"
version = "0.1.0"
edition = "2024"

[dependencies]

dynatos-context = { workspace = true }
dynatos-util    = { workspace = true }

derive_more          = { workspace = true, features = ["full"] }
duplicate            = { workspace = true }
extend               = { workspace = true }
futures              = { workspace = true }
itertools            = { workspace = true }
parking_lot          = { workspace = true }
petgraph             = { workspace = true }
pin-project          = { workspace = true }
priority-queue       = { workspace = true }
scopeguard           = { workspace = true }
tokio                = { workspace = true, features = ["sync"] }
tracing              = { workspace = true }
wasm-bindgen-futures = { workspace = true }
zutil-cloned         = { workspace = true }

[lints]
workspace = true
