[package]
edition = "2021"
name = "dynatos-logger"
version = "0.1.0"

[dependencies]

anyhow = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true, features = ["env-filter"] }
tracing-web = { workspace = true }
