[workspace]

members = ["counter", "counter-no-macros", "router", "query"]
resolver = "2"

[workspace.dependencies]

# Parent workspace members
dynatos = { path = "../dynatos" }
dynatos-context = { path = "../dynatos-context" }
dynatos-html = { path = "../dynatos-html" }
dynatos-reactive = { path = "../dynatos-reactive" }
dynatos-router = { path = "../dynatos-router" }
dynatos-title = { path = "../dynatos-title" }
dynatos-util = { path = "../dynatos-util" }

anyhow = "1.0.94"
console_error_panic_hook = "0.1.7"
duplicate = "2.0.0"
extend = "1.2.0"
itertools = "0.13.0"
js-sys = "0.3.76"
tracing = "0.1.41"
tracing-subscriber = "0.3.19"
tracing-web = "0.1.3"
url = "2.5.4"
wasm-bindgen = "0.2.99"
web-sys = "0.3.76"
