[workspace]

members = ["counter"]
resolver = "2"

[workspace.dependencies]

# Parent workspace members
dynatos = { path = "../dynatos" }
dynatos-logger = { path = "../dynatos-logger" }
dynatos-reactive = { path = "../dynatos-reactive" }
dynatos-util = { path = "../dynatos-util" }

anyhow = "1.0.79"
console_error_panic_hook = "0.1.7"
duplicate = "1.0.0"
extend = "1.2.0"
js-sys = "0.3.67"
tracing = "0.1.40"
wasm-bindgen = "0.2.90"
web-sys = "0.3.67"
