[package]
name = "dynatos-reactive-sync"
version = "0.1.0"
edition = "2021"

[dependencies]

derive_more = { workspace = true, features = ["full"] }
parking_lot = { workspace = true, features = ["send_guard"], optional = true }

[lints]
workspace = true

[features]
sync = ["dep:parking_lot"]
